### ISSUE TITLE
Error generating highlights with --no-proc-async on MacOS

### ISSUE THREAD

**Issue by coke** [perl6/doc#1128]
See #1127

When I run

    perl6 htmlify --sparse --no-proc-async

I get errors of the form:

```
Highlights is reading /Users/coke/sandbox/perl6-doc
Error: EISDIR: illegal operation on a directory, read
  at Object.fs.readSync (fs.js:656:19)
  at tryReadSync (fs.js:457:20)
  at Object.fs.readFileSync (fs.js:494:19)
  at foo (/Users/coke/sandbox/perl6-doc/highlights/highlight-file.coffee:13:6)
  at Object.<anonymous> (/Users/coke/sandbox/perl6-doc/highlights/highlight-file.coffee:16:17)
  at Object.<anonymous> (/Users/coke/sandbox/perl6-doc/highlights/highlight-file.coffee:3:1)
  at Module._compile (module.js:571:32)
  at Object.exports.run (/Users/coke/sandbox/perl6-doc/highlights/node_modules/coffee-script/lib/coffee-script/coffee-script.js:166:23)
  at compileScript (/Users/coke/sandbox/perl6-doc/highlights/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/Users/coke/sandbox/perl6-doc/highlights/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/Users/coke/sandbox/perl6-doc/highlights/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/Users/coke/sandbox/perl6-doc/highlights/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.runMain (module.js:605:10)
  at run (bootstrap_node.js:420:7)
  at startup (bootstrap_node.js:139:9)
  at bootstrap_node.js:535:3
```

**Comment by samcv** [comment]
This was fixed in https://github.com/perl6/doc/commit/f7ff9b7496a57b7cfa1d3ed6c745b4ce865504ae closing.
