### ISSUE TITLE
Bad installation instructions

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1457]
The [contributing doc](https://github.com/perl6/doc/blob/master/CONTRIBUTING.md#building-the-documentation) says `highlights (optional; requires only nodejs and at least GCC-4.8 on Linux to be installed. Running make will set everything up for you.)`

I have:
```
nodejs is already the newest version (4.8.2~dfsg-1).
gcc version 6.3.0 20170516 (Debian 6.3.0-18) 
```

However, the build dies with:

```
/bin/sh: 4: npm: not found
Makefile:11: recipe for target 'init-highlights' failed
make: *** [init-highlights] Error 127
```

So clearly something is amiss. What is it?

**Comment by zoffixznet** [comment]
I tried `sudo apt-get install npm` and now it dies with the error below. This is currently breaking the doc build, since hack got upgraded:

```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/doc.perl6.org/doc/highlights/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/node_modules/highlights/node_modules/first-mate/lib/grammar.js:10:16)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/node_modules/highlights/node_modules/first-mate/lib/grammar.js:380:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/doc.perl6.org/doc/highlights/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/node_modules/highlights/node_modules/first-mate/lib/grammar-registry.js:12:13)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/node_modules/highlights/node_modules/first-mate/lib/grammar-registry.js:268:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/doc.perl6.org/doc/highlights/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/node_modules/highlights/node_modules/first-mate/lib/first-mate.js:4:22)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/node_modules/highlights/node_modules/first-mate/lib/first-mate.js:8:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/doc.perl6.org/doc/highlights/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/node_modules/highlights/lib/highlights.js:14:21)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/node_modules/highlights/lib/highlights.js:420:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/doc.perl6.org/doc/highlights/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/highlight-filename-from-stdin.coffee:3:14)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/highlight-filename-from-stdin.coffee:3:1)
    at Module._compile (module.js:409:26)
    at Object.exports.run (/home/doc.perl6.org/doc/highlights/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/home/doc.perl6.org/doc/highlights/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
    at compilePath (/home/doc.perl6.org/doc/highlights/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/home/doc.perl6.org/doc/highlights/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/home/doc.perl6.org/doc/highlights/node_modules/coffee-script/bin/coffee:15:45)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by coke** [comment]
The versions of node & npm that are installed seem quite old compared to those listed on the node site.

I found https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-debian-8#how-to-install-using-nvm, but then we're not using the system packages.

**Comment by coke** [comment]
FWIW:
```
root@hack:/home/doc.perl6.org# nodejs -v
v4.8.2
root@hack:/home/doc.perl6.org# node -v
v8.4.0
root@hack:/home/doc.perl6.org# which nodejs
/usr/bin/nodejs
root@hack:/home/doc.perl6.org# which node
/usr/local/bin/node
```

**Comment by coke** [comment]
I think the problem was that we had an old highlights directory that predated the new tooling install., I removed highlights, did a make init-highlights, killed off the stalled jobs that were blocking the cron job from running, and the site seems to be updating correctly now.
