### ISSUE TITLE
cannot build html

### ISSUE THREAD

**Issue by fluca1978** [perl6/doc#1701]
I'm trying to build the html locally, but getting the following stack trace:

```
 258/258: doc/Type/atomicint.pod6                  => type/atomicint
Starting highlights worker thread
Composing doc registry ...
Writing programs document for Perl 6 ...
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/luca/tmp/doc/highlights/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/node_modules/first-mate/lib/grammar.js:10:16)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/node_modules/first-mate/lib/grammar.js:380:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/luca/tmp/doc/highlights/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/node_modules/first-mate/lib/grammar-registry.js:12:13)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/node_modules/first-mate/lib/grammar-registry.js:268:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/luca/tmp/doc/highlights/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/node_modules/first-mate/lib/first-mate.js:4:22)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/node_modules/first-mate/lib/first-mate.js:8:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/luca/tmp/doc/highlights/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/node_modules/highlights/lib/highlights.js:14:21)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/node_modules/highlights/lib/highlights.js:420:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (/home/luca/tmp/doc/highlights/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/highlight-filename-from-stdin.coffee:3:14)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/highlight-filename-from-stdin.coffee:3:1)
    at Module._compile (module.js:409:26)
    at Object.exports.run (/home/luca/tmp/doc/highlights/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/home/luca/tmp/doc/highlights/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
    at compilePath (/home/luca/tmp/doc/highlights/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/home/luca/tmp/doc/highlights/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/home/luca/tmp/doc/highlights/node_modules/coffee-script/bin/coffee:15:45)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

I'm runnin gon ubuntu, with nodejs 4.7.2, documentation head 90659494967cc7ac3b312c1cf327cce8facbc272.

**Comment by AlexDaniel** [comment]
I wonder if we can have ``make build`` that would perform less operations (without syntax highlighting and other stuff; for contributors) and ``make full-build`` which will do everything. I always get some troubles when building it (even though those are always easy to fix).

**Comment by fluca1978** [comment]
Apparently the version of node installed by Ubuntu is a lot old.
I downloaded and installed v 8.9.2 from nodejs.org, removed the content of the highlights/node_modules directory and fire a make again.

Therefore, it was a problem of the node version begin too old.

**Comment by JJ** [comment]
You should never use node, or any other language interpreter for that
matter, from the repos. It's better to use version managers, like nvm in
the case of node.
